// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "OpenClimb",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "OpenClimb",
            targets: ["AppModule"],
            bundleIdentifier: "CTST.OpenClimb",
            teamIdentifier: "FBFGPPRU68",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Access all app capabilities")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Model/HoldsDetector.mlmodelc"),
                .copy("Resources/sample.mov")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)